"""Node replacement table and its registration entry point.

An ``io.NodeReplace`` entry migrates a saved workflow from a retired node onto its
successor with no rewiring.
"""

from __future__ import annotations

from comfy_api.latest import ComfyAPI, io

from .. import log

logger = log.get_logger("compat")

#: Every migration the pack offers, keyed on ``(old_node_id, new_node_id)`` at registration.
REPLACEMENTS: tuple[io.NodeReplace, ...] = (
    io.NodeReplace(
        new_node_id="WASImageCropFaceNative",
        old_node_id="Image Crop Face",
        old_widget_ids=["crop_padding_factor", "cascade_xml"],
        input_mapping=[
            {"new_id": "image", "old_id": "image"},
            {"new_id": "crop_padding_factor", "old_id": "crop_padding_factor"},
            {"new_id": "cascade", "old_id": "cascade_xml"},
        ],
        output_mapping=[{"new_idx": 0, "old_idx": 0}, {"new_idx": 1, "old_idx": 1}],
    ),
    io.NodeReplace(
        new_node_id="WASImageGradientMapNative",
        old_node_id="Image Gradient Map",
        old_widget_ids=["flip_left_right"],
        input_mapping=[
            {"new_id": "image", "old_id": "image"},
            {"new_id": "flip_left_right", "old_id": "flip_left_right"},
            {"new_id": "gradient_image", "old_id": "gradient_image"},
        ],
        output_mapping=[{"new_idx": 0, "old_idx": 0}],
    ),
    io.NodeReplace(
        new_node_id="Image Batch",
        old_node_id="WASImageBatchAutogrow",
        old_widget_ids=[],
        input_mapping=[
            {"new_id": "images_a", "old_id": "images.images_a"},
            {"new_id": "images_b", "old_id": "images.images_b"},
            {"new_id": "images_c", "old_id": "images.images_c"},
            {"new_id": "images_d", "old_id": "images.images_d"},
            {"new_id": "images_e", "old_id": "images.images_e"},
            {"new_id": "images_f", "old_id": "images.images_f"},
            {"new_id": "images_g", "old_id": "images.images_g"},
            {"new_id": "images_h", "old_id": "images.images_h"},
            {"new_id": "images_i", "old_id": "images.images_i"},
            {"new_id": "images_j", "old_id": "images.images_j"},
            {"new_id": "images_k", "old_id": "images.images_k"},
            {"new_id": "images_l", "old_id": "images.images_l"},
            {"new_id": "images_m", "old_id": "images.images_m"},
            {"new_id": "images_n", "old_id": "images.images_n"},
            {"new_id": "images_o", "old_id": "images.images_o"},
            {"new_id": "images_p", "old_id": "images.images_p"},
            {"new_id": "images_q", "old_id": "images.images_q"},
            {"new_id": "images_r", "old_id": "images.images_r"},
            {"new_id": "images_s", "old_id": "images.images_s"},
            {"new_id": "images_t", "old_id": "images.images_t"},
            {"new_id": "images_u", "old_id": "images.images_u"},
            {"new_id": "images_v", "old_id": "images.images_v"},
            {"new_id": "images_w", "old_id": "images.images_w"},
            {"new_id": "images_x", "old_id": "images.images_x"},
            {"new_id": "images_y", "old_id": "images.images_y"},
            {"new_id": "images_z", "old_id": "images.images_z"},
        ],
        output_mapping=[{"new_idx": 0, "old_idx": 0}, {"new_idx": 1, "old_idx": 1}],
    ),
    io.NodeReplace(
        new_node_id="Lora Loader",
        old_node_id="Load Lora",
        old_widget_ids=["lora_name", "strength_model", "strength_clip"],
        input_mapping=[
            {"new_id": "model", "old_id": "model"},
            {"new_id": "clip", "old_id": "clip"},
            {"new_id": "lora_name", "old_id": "lora_name"},
            {"new_id": "strength_model", "old_id": "strength_model"},
            {"new_id": "strength_clip", "old_id": "strength_clip"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
        ],
    ),
    io.NodeReplace(
        new_node_id="Number to String",
        old_node_id="Number to Text",
        old_widget_ids=[],
        input_mapping=[{"new_id": "number", "old_id": "number"}],
        output_mapping=[{"new_idx": 0, "old_idx": 0}],
    ),
    # The old menu is not carried across. Its default named every terminology, which the
    # empty pick box already answers with, and any other value is a term name typed again.
    io.NodeReplace(
        new_node_id="WASNoodleSoupPick",
        old_node_id="WASNoodleSoupTermList",
        old_widget_ids=["term", "limit", "term_name"],
        input_mapping=[
            {"new_id": "limit", "old_id": "limit"},
            {"new_id": "term", "old_id": "term_name"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
            {"new_idx": 3, "old_idx": 3},
        ],
    ),
    # Ids promoted from WAS Extras, onto a WAS or WASNS prefix over an unchanged surface.
    io.NodeReplace(
        new_node_id="WASBLVAEEncode",
        old_node_id="BLVAEEncode",
        old_widget_ids=["tiled", "tile_size", "store_or_load_latent", "remove_latent_on_load", "delete_workflow_latent"],
        input_mapping=[
            {"new_id": "vae", "old_id": "vae"},
            {"new_id": "tiled", "old_id": "tiled"},
            {"new_id": "tile_size", "old_id": "tile_size"},
            {"new_id": "store_or_load_latent", "old_id": "store_or_load_latent"},
            {"new_id": "remove_latent_on_load", "old_id": "remove_latent_on_load"},
            {"new_id": "delete_workflow_latent", "old_id": "delete_workflow_latent"},
            {"new_id": "image", "old_id": "image"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASCLIPTextEncodeList",
        old_node_id="CLIPTextEncodeList",
        old_widget_ids=["text"],
        input_mapping=[
            {"new_id": "clip", "old_id": "clip"},
            {"new_id": "token_normalization", "old_id": "token_normalization"},
            {"new_id": "weight_interpretation", "old_id": "weight_interpretation"},
            {"new_id": "text", "old_id": "text"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASCLIPTextEncodeSequence2",
        old_node_id="CLIPTextEncodeSequence2",
        old_widget_ids=["frame_count", "text"],
        input_mapping=[
            {"new_id": "clip", "old_id": "clip"},
            {"new_id": "token_normalization", "old_id": "token_normalization"},
            {"new_id": "weight_interpretation", "old_id": "weight_interpretation"},
            {"new_id": "cond_keyframes_type", "old_id": "cond_keyframes_type"},
            {"new_id": "frame_count", "old_id": "frame_count"},
            {"new_id": "text", "old_id": "text"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASConditioningBlend",
        old_node_id="ConditioningBlend",
        old_widget_ids=["blending_strength", "seed"],
        input_mapping=[
            {"new_id": "conditioning_a", "old_id": "conditioning_a"},
            {"new_id": "conditioning_b", "old_id": "conditioning_b"},
            {"new_id": "blending_mode", "old_id": "blending_mode"},
            {"new_id": "blending_strength", "old_id": "blending_strength"},
            {"new_id": "seed", "old_id": "seed"},
            {"new_id": "conditioning_c", "old_id": "conditioning_c"},
            {"new_id": "conditioning_d", "old_id": "conditioning_d"},
            {"new_id": "conditioning_e", "old_id": "conditioning_e"},
            {"new_id": "conditioning_f", "old_id": "conditioning_f"},
            {"new_id": "conditioning_g", "old_id": "conditioning_g"},
            {"new_id": "conditioning_h", "old_id": "conditioning_h"},
            {"new_id": "conditioning_i", "old_id": "conditioning_i"},
            {"new_id": "conditioning_j", "old_id": "conditioning_j"},
            {"new_id": "conditioning_k", "old_id": "conditioning_k"},
            {"new_id": "conditioning_l", "old_id": "conditioning_l"},
            {"new_id": "conditioning_m", "old_id": "conditioning_m"},
            {"new_id": "conditioning_n", "old_id": "conditioning_n"},
            {"new_id": "conditioning_o", "old_id": "conditioning_o"},
            {"new_id": "conditioning_p", "old_id": "conditioning_p"},
            {"new_id": "conditioning_q", "old_id": "conditioning_q"},
            {"new_id": "conditioning_r", "old_id": "conditioning_r"},
            {"new_id": "conditioning_s", "old_id": "conditioning_s"},
            {"new_id": "conditioning_t", "old_id": "conditioning_t"},
            {"new_id": "conditioning_u", "old_id": "conditioning_u"},
            {"new_id": "conditioning_v", "old_id": "conditioning_v"},
            {"new_id": "conditioning_w", "old_id": "conditioning_w"},
            {"new_id": "conditioning_x", "old_id": "conditioning_x"},
            {"new_id": "conditioning_y", "old_id": "conditioning_y"},
            {"new_id": "conditioning_z", "old_id": "conditioning_z"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASDebugInput",
        old_node_id="DebugInput",
        input_mapping=[
            {"new_id": "input", "old_id": "input"},
        ],
        output_mapping=[
        ],
    ),
    io.NodeReplace(
        new_node_id="WASKSamplerSeq",
        old_node_id="KSamplerSeq",
        old_widget_ids=["seed", "alternate_values", "steps", "cfg", "sequence_loop_count", "use_conditioning_slerp", "cond_slerp_strength", "use_latent_interpolation", "latent_interp_strength", "denoise_start", "denoise_seq", "unsample_latents"],
        input_mapping=[
            {"new_id": "model", "old_id": "model"},
            {"new_id": "seed", "old_id": "seed"},
            {"new_id": "seed_mode_seq", "old_id": "seed_mode_seq"},
            {"new_id": "alternate_values", "old_id": "alternate_values"},
            {"new_id": "steps", "old_id": "steps"},
            {"new_id": "cfg", "old_id": "cfg"},
            {"new_id": "sampler_name", "old_id": "sampler_name"},
            {"new_id": "scheduler", "old_id": "scheduler"},
            {"new_id": "sequence_loop_count", "old_id": "sequence_loop_count"},
            {"new_id": "positive_seq", "old_id": "positive_seq"},
            {"new_id": "negative_seq", "old_id": "negative_seq"},
            {"new_id": "use_conditioning_slerp", "old_id": "use_conditioning_slerp"},
            {"new_id": "cond_slerp_strength", "old_id": "cond_slerp_strength"},
            {"new_id": "latent_image", "old_id": "latent_image"},
            {"new_id": "use_latent_interpolation", "old_id": "use_latent_interpolation"},
            {"new_id": "latent_interpolation_mode", "old_id": "latent_interpolation_mode"},
            {"new_id": "latent_interp_strength", "old_id": "latent_interp_strength"},
            {"new_id": "denoise_start", "old_id": "denoise_start"},
            {"new_id": "denoise_seq", "old_id": "denoise_seq"},
            {"new_id": "unsample_latents", "old_id": "unsample_latents"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASKSamplerSeq2",
        old_node_id="KSamplerSeq2",
        old_widget_ids=["seed", "alternate_values", "steps", "cfg", "frame_count", "cond_keyframes", "use_conditioning_slerp", "cond_slerp_strength", "use_latent_interpolation", "latent_interp_strength", "denoise_start", "denoise_seq", "unsample_latents", "inject_noise", "noise_strength", "denoise_sine", "denoise_max", "seed_keying", "seed_divisor"],
        input_mapping=[
            {"new_id": "model", "old_id": "model"},
            {"new_id": "seed", "old_id": "seed"},
            {"new_id": "seed_mode_seq", "old_id": "seed_mode_seq"},
            {"new_id": "alternate_values", "old_id": "alternate_values"},
            {"new_id": "steps", "old_id": "steps"},
            {"new_id": "cfg", "old_id": "cfg"},
            {"new_id": "sampler_name", "old_id": "sampler_name"},
            {"new_id": "scheduler", "old_id": "scheduler"},
            {"new_id": "frame_count", "old_id": "frame_count"},
            {"new_id": "cond_keyframes", "old_id": "cond_keyframes"},
            {"new_id": "positive_seq", "old_id": "positive_seq"},
            {"new_id": "negative_seq", "old_id": "negative_seq"},
            {"new_id": "use_conditioning_slerp", "old_id": "use_conditioning_slerp"},
            {"new_id": "cond_slerp_strength", "old_id": "cond_slerp_strength"},
            {"new_id": "latent_image", "old_id": "latent_image"},
            {"new_id": "use_latent_interpolation", "old_id": "use_latent_interpolation"},
            {"new_id": "latent_interpolation_mode", "old_id": "latent_interpolation_mode"},
            {"new_id": "latent_interp_strength", "old_id": "latent_interp_strength"},
            {"new_id": "denoise_start", "old_id": "denoise_start"},
            {"new_id": "denoise_seq", "old_id": "denoise_seq"},
            {"new_id": "unsample_latents", "old_id": "unsample_latents"},
            {"new_id": "inject_noise", "old_id": "inject_noise"},
            {"new_id": "noise_strength", "old_id": "noise_strength"},
            {"new_id": "denoise_sine", "old_id": "denoise_sine"},
            {"new_id": "denoise_max", "old_id": "denoise_max"},
            {"new_id": "seed_keying", "old_id": "seed_keying"},
            {"new_id": "seed_keying_mode", "old_id": "seed_keying_mode"},
            {"new_id": "seed_divisor", "old_id": "seed_divisor"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSAdaptiveDifferenceLatentUpscale",
        old_node_id="WAS_AdaptiveDifferenceLatentUpscale",
        old_widget_ids=["scale", "diff_blur_sigma", "threshold", "softness", "weight_power", "weight_blur_sigma", "temporal_ema", "enable_directional_damping", "damping_strength", "damping_grad_blur_sigma", "damping_threshold", "damping_softness", "damping_power", "damping_mask_blur_sigma", "damping_highpass_sigma", "damping_temporal_ema", "output_mask_pixel_scale"],
        input_mapping=[
            {"new_id": "latent", "old_id": "latent"},
            {"new_id": "scale", "old_id": "scale"},
            {"new_id": "smooth_mode", "old_id": "smooth_mode"},
            {"new_id": "diff_blur_sigma", "old_id": "diff_blur_sigma"},
            {"new_id": "threshold", "old_id": "threshold"},
            {"new_id": "softness", "old_id": "softness"},
            {"new_id": "weight_power", "old_id": "weight_power"},
            {"new_id": "weight_blur_sigma", "old_id": "weight_blur_sigma"},
            {"new_id": "temporal_ema", "old_id": "temporal_ema"},
            {"new_id": "enable_directional_damping", "old_id": "enable_directional_damping"},
            {"new_id": "damping_strength", "old_id": "damping_strength"},
            {"new_id": "damping_gate_mode", "old_id": "damping_gate_mode"},
            {"new_id": "damping_grad_blur_sigma", "old_id": "damping_grad_blur_sigma"},
            {"new_id": "damping_threshold", "old_id": "damping_threshold"},
            {"new_id": "damping_softness", "old_id": "damping_softness"},
            {"new_id": "damping_power", "old_id": "damping_power"},
            {"new_id": "damping_mask_blur_sigma", "old_id": "damping_mask_blur_sigma"},
            {"new_id": "damping_highpass_sigma", "old_id": "damping_highpass_sigma"},
            {"new_id": "damping_temporal_ema", "old_id": "damping_temporal_ema"},
            {"new_id": "preview_mode", "old_id": "preview_mode"},
            {"new_id": "output_mask_pixel_scale", "old_id": "output_mask_pixel_scale"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSApplyLUT",
        old_node_id="WASApplyLUT",
        old_widget_ids=["strength", "use_threads", "threads"],
        input_mapping=[
            {"new_id": "image", "old_id": "image"},
            {"new_id": "lut", "old_id": "lut"},
            {"new_id": "strength", "old_id": "strength"},
            {"new_id": "use_threads", "old_id": "use_threads"},
            {"new_id": "threads", "old_id": "threads"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSApplyReweightedLoRA",
        old_node_id="WASApplyReweightedLoRA",
        old_widget_ids=["strength_model", "strength_clip", "global_scale", "front_scale", "mid_scale", "back_scale", "last_block_scale", "filter_by_block_range", "save_reweighted", "output_filename", "verify_roundtrip"],
        input_mapping=[
            {"new_id": "model", "old_id": "model"},
            {"new_id": "clip", "old_id": "clip"},
            {"new_id": "lora_name", "old_id": "lora_name"},
            {"new_id": "strength_model", "old_id": "strength_model"},
            {"new_id": "strength_clip", "old_id": "strength_clip"},
            {"new_id": "global_scale", "old_id": "global_scale"},
            {"new_id": "front_scale", "old_id": "front_scale"},
            {"new_id": "mid_scale", "old_id": "mid_scale"},
            {"new_id": "back_scale", "old_id": "back_scale"},
            {"new_id": "last_block_scale", "old_id": "last_block_scale"},
            {"new_id": "scale_target", "old_id": "scale_target"},
            {"new_id": "block_preset", "old_id": "block_preset"},
            {"new_id": "filter_by_block_range", "old_id": "filter_by_block_range"},
            {"new_id": "save_reweighted", "old_id": "save_reweighted"},
            {"new_id": "output_filename", "old_id": "output_filename"},
            {"new_id": "verify_roundtrip", "old_id": "verify_roundtrip"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSCameraMotionTrajectory",
        old_node_id="WASCameraMotionTrajectory",
        old_widget_ids=["num_frames", "trajectory_spec", "enable_camera_shake", "shake_position_amplitude", "shake_rotation_amplitude", "shake_seed"],
        input_mapping=[
            {"new_id": "image", "old_id": "image"},
            {"new_id": "num_frames", "old_id": "num_frames"},
            {"new_id": "trajectory_spec", "old_id": "trajectory_spec"},
            {"new_id": "edge_mode", "old_id": "edge_mode"},
            {"new_id": "enable_camera_shake", "old_id": "enable_camera_shake"},
            {"new_id": "shake_position_amplitude", "old_id": "shake_position_amplitude"},
            {"new_id": "shake_rotation_amplitude", "old_id": "shake_rotation_amplitude"},
            {"new_id": "shake_seed", "old_id": "shake_seed"},
            {"new_id": "depth_map", "old_id": "depth_map"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSChannelWaveform",
        old_node_id="WASChannelWaveform",
        old_widget_ids=["waveform_height"],
        input_mapping=[
            {"new_id": "image", "old_id": "image"},
            {"new_id": "waveform_height", "old_id": "waveform_height"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
            {"new_idx": 3, "old_idx": 3},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSCombineLUT",
        old_node_id="WASCombineLUT",
        old_widget_ids=["strength", "output_size"],
        input_mapping=[
            {"new_id": "lut_a", "old_id": "lut_a"},
            {"new_id": "lut_b", "old_id": "lut_b"},
            {"new_id": "mode", "old_id": "mode"},
            {"new_id": "strength", "old_id": "strength"},
            {"new_id": "output_size", "old_id": "output_size"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSImageTileExtract",
        old_node_id="WASImageTileExtract",
        old_widget_ids=["border_width", "border_color"],
        input_mapping=[
            {"new_id": "images", "old_id": "images"},
            {"new_id": "border_width", "old_id": "border_width"},
            {"new_id": "border_color", "old_id": "border_color"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
            {"new_idx": 3, "old_idx": 3},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSImageTileShuffle",
        old_node_id="WASImageTileShuffle",
        old_widget_ids=["max_tiles", "seed", "border_width", "border_color"],
        input_mapping=[
            {"new_id": "images", "old_id": "images"},
            {"new_id": "max_tiles", "old_id": "max_tiles"},
            {"new_id": "seed", "old_id": "seed"},
            {"new_id": "border_width", "old_id": "border_width"},
            {"new_id": "border_color", "old_id": "border_color"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSLatentContrastLimitedDetailBoost",
        old_node_id="WASLatentContrastLimitedDetailBoost",
        old_widget_ids=["sigma_small", "sigma_large", "gain", "limit", "rms_sigma", "rms_floor", "edge_protect", "edge_sigma", "edge_threshold", "edge_softness", "preview_mask_scale"],
        input_mapping=[
            {"new_id": "latent", "old_id": "latent"},
            {"new_id": "sigma_small", "old_id": "sigma_small"},
            {"new_id": "sigma_large", "old_id": "sigma_large"},
            {"new_id": "gain", "old_id": "gain"},
            {"new_id": "limit", "old_id": "limit"},
            {"new_id": "rms_sigma", "old_id": "rms_sigma"},
            {"new_id": "rms_floor", "old_id": "rms_floor"},
            {"new_id": "edge_protect", "old_id": "edge_protect"},
            {"new_id": "edge_sigma", "old_id": "edge_sigma"},
            {"new_id": "edge_threshold", "old_id": "edge_threshold"},
            {"new_id": "edge_softness", "old_id": "edge_softness"},
            {"new_id": "preview_mask_scale", "old_id": "preview_mask_scale"},
            {"new_id": "preview_mode", "old_id": "preview_mode"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSLatentUpscaleHybrid",
        old_node_id="WASLatentUpscaleHybrid",
        old_widget_ids=["scale", "pre_blur_sigma_px", "canny_threshold1", "canny_threshold2", "canny_l2gradient", "dilate_radius_px", "feather_sigma_px", "mask_min", "mask_max", "use_nearest_exact", "video_decode_horizontal_tiles", "video_decode_vertical_tiles", "video_decode_overlap_latent", "video_decode_last_frame_fix", "video_decode_enable_cudnn"],
        input_mapping=[
            {"new_id": "latent", "old_id": "latent"},
            {"new_id": "vae", "old_id": "vae"},
            {"new_id": "scale", "old_id": "scale"},
            {"new_id": "pre_blur_sigma_px", "old_id": "pre_blur_sigma_px"},
            {"new_id": "canny_threshold1", "old_id": "canny_threshold1"},
            {"new_id": "canny_threshold2", "old_id": "canny_threshold2"},
            {"new_id": "canny_l2gradient", "old_id": "canny_l2gradient"},
            {"new_id": "dilate_radius_px", "old_id": "dilate_radius_px"},
            {"new_id": "feather_sigma_px", "old_id": "feather_sigma_px"},
            {"new_id": "mask_min", "old_id": "mask_min"},
            {"new_id": "mask_max", "old_id": "mask_max"},
            {"new_id": "use_nearest_exact", "old_id": "use_nearest_exact"},
            {"new_id": "output_mask_resolution", "old_id": "output_mask_resolution"},
            {"new_id": "video_decode_horizontal_tiles", "old_id": "video_decode_horizontal_tiles"},
            {"new_id": "video_decode_vertical_tiles", "old_id": "video_decode_vertical_tiles"},
            {"new_id": "video_decode_overlap_latent", "old_id": "video_decode_overlap_latent"},
            {"new_id": "video_decode_last_frame_fix", "old_id": "video_decode_last_frame_fix"},
            {"new_id": "video_decode_enable_cudnn", "old_id": "video_decode_enable_cudnn"},
            {"new_id": "donor_latent", "old_id": "donor_latent"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSLoadLUT",
        old_node_id="WASLoadLUT",
        old_widget_ids=["builtin_size", "custom_ev", "custom_contrast", "custom_saturation", "custom_vibrance", "custom_gamma", "custom_temperature", "custom_tint", "custom_red_balance", "custom_green_balance", "custom_blue_balance"],
        input_mapping=[
            {"new_id": "look", "old_id": "look"},
            {"new_id": "builtin_size", "old_id": "builtin_size"},
            {"new_id": "custom_ev", "old_id": "custom_ev"},
            {"new_id": "custom_contrast", "old_id": "custom_contrast"},
            {"new_id": "custom_saturation", "old_id": "custom_saturation"},
            {"new_id": "custom_vibrance", "old_id": "custom_vibrance"},
            {"new_id": "custom_gamma", "old_id": "custom_gamma"},
            {"new_id": "custom_temperature", "old_id": "custom_temperature"},
            {"new_id": "custom_tint", "old_id": "custom_tint"},
            {"new_id": "custom_red_balance", "old_id": "custom_red_balance"},
            {"new_id": "custom_green_balance", "old_id": "custom_green_balance"},
            {"new_id": "custom_blue_balance", "old_id": "custom_blue_balance"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSPowerLoraMerger",
        old_node_id="WASPowerLoraMerger",
        old_widget_ids=["output_filename", "output_model_strength", "output_clip_strength", "lora_1_enabled", "lora_1_weight", "lora_2_enabled", "lora_2_weight", "lora_3_enabled", "lora_3_weight", "lora_4_enabled", "lora_4_weight", "lora_5_enabled", "lora_5_weight", "lora_6_enabled", "lora_6_weight", "lora_7_enabled", "lora_7_weight", "lora_8_enabled", "lora_8_weight", "lora_9_enabled", "lora_9_weight", "lora_10_enabled", "lora_10_weight", "lora_11_enabled", "lora_11_weight", "lora_12_enabled", "lora_12_weight", "lora_13_enabled", "lora_13_weight", "lora_14_enabled", "lora_14_weight", "lora_15_enabled", "lora_15_weight", "lora_16_enabled", "lora_16_weight", "lora_17_enabled", "lora_17_weight", "lora_18_enabled", "lora_18_weight", "lora_19_enabled", "lora_19_weight", "lora_20_enabled", "lora_20_weight", "lora_21_enabled", "lora_21_weight", "lora_22_enabled", "lora_22_weight", "lora_23_enabled", "lora_23_weight", "lora_24_enabled", "lora_24_weight", "lora_25_enabled", "lora_25_weight", "lora_26_enabled", "lora_26_weight"],
        input_mapping=[
            {"new_id": "output_filename", "old_id": "output_filename"},
            {"new_id": "output_model_strength", "old_id": "output_model_strength"},
            {"new_id": "output_clip_strength", "old_id": "output_clip_strength"},
            {"new_id": "mode", "old_id": "mode"},
            {"new_id": "block_mix_recipe", "old_id": "block_mix_recipe"},
            {"new_id": "model", "old_id": "model"},
            {"new_id": "clip", "old_id": "clip"},
            {"new_id": "options", "old_id": "options"},
            {"new_id": "lora_1_enabled", "old_id": "lora_1_enabled"},
            {"new_id": "lora_1", "old_id": "lora_1"},
            {"new_id": "lora_1_weight", "old_id": "lora_1_weight"},
            {"new_id": "lora_2_enabled", "old_id": "lora_2_enabled"},
            {"new_id": "lora_2", "old_id": "lora_2"},
            {"new_id": "lora_2_weight", "old_id": "lora_2_weight"},
            {"new_id": "lora_3_enabled", "old_id": "lora_3_enabled"},
            {"new_id": "lora_3", "old_id": "lora_3"},
            {"new_id": "lora_3_weight", "old_id": "lora_3_weight"},
            {"new_id": "lora_4_enabled", "old_id": "lora_4_enabled"},
            {"new_id": "lora_4", "old_id": "lora_4"},
            {"new_id": "lora_4_weight", "old_id": "lora_4_weight"},
            {"new_id": "lora_5_enabled", "old_id": "lora_5_enabled"},
            {"new_id": "lora_5", "old_id": "lora_5"},
            {"new_id": "lora_5_weight", "old_id": "lora_5_weight"},
            {"new_id": "lora_6_enabled", "old_id": "lora_6_enabled"},
            {"new_id": "lora_6", "old_id": "lora_6"},
            {"new_id": "lora_6_weight", "old_id": "lora_6_weight"},
            {"new_id": "lora_7_enabled", "old_id": "lora_7_enabled"},
            {"new_id": "lora_7", "old_id": "lora_7"},
            {"new_id": "lora_7_weight", "old_id": "lora_7_weight"},
            {"new_id": "lora_8_enabled", "old_id": "lora_8_enabled"},
            {"new_id": "lora_8", "old_id": "lora_8"},
            {"new_id": "lora_8_weight", "old_id": "lora_8_weight"},
            {"new_id": "lora_9_enabled", "old_id": "lora_9_enabled"},
            {"new_id": "lora_9", "old_id": "lora_9"},
            {"new_id": "lora_9_weight", "old_id": "lora_9_weight"},
            {"new_id": "lora_10_enabled", "old_id": "lora_10_enabled"},
            {"new_id": "lora_10", "old_id": "lora_10"},
            {"new_id": "lora_10_weight", "old_id": "lora_10_weight"},
            {"new_id": "lora_11_enabled", "old_id": "lora_11_enabled"},
            {"new_id": "lora_11", "old_id": "lora_11"},
            {"new_id": "lora_11_weight", "old_id": "lora_11_weight"},
            {"new_id": "lora_12_enabled", "old_id": "lora_12_enabled"},
            {"new_id": "lora_12", "old_id": "lora_12"},
            {"new_id": "lora_12_weight", "old_id": "lora_12_weight"},
            {"new_id": "lora_13_enabled", "old_id": "lora_13_enabled"},
            {"new_id": "lora_13", "old_id": "lora_13"},
            {"new_id": "lora_13_weight", "old_id": "lora_13_weight"},
            {"new_id": "lora_14_enabled", "old_id": "lora_14_enabled"},
            {"new_id": "lora_14", "old_id": "lora_14"},
            {"new_id": "lora_14_weight", "old_id": "lora_14_weight"},
            {"new_id": "lora_15_enabled", "old_id": "lora_15_enabled"},
            {"new_id": "lora_15", "old_id": "lora_15"},
            {"new_id": "lora_15_weight", "old_id": "lora_15_weight"},
            {"new_id": "lora_16_enabled", "old_id": "lora_16_enabled"},
            {"new_id": "lora_16", "old_id": "lora_16"},
            {"new_id": "lora_16_weight", "old_id": "lora_16_weight"},
            {"new_id": "lora_17_enabled", "old_id": "lora_17_enabled"},
            {"new_id": "lora_17", "old_id": "lora_17"},
            {"new_id": "lora_17_weight", "old_id": "lora_17_weight"},
            {"new_id": "lora_18_enabled", "old_id": "lora_18_enabled"},
            {"new_id": "lora_18", "old_id": "lora_18"},
            {"new_id": "lora_18_weight", "old_id": "lora_18_weight"},
            {"new_id": "lora_19_enabled", "old_id": "lora_19_enabled"},
            {"new_id": "lora_19", "old_id": "lora_19"},
            {"new_id": "lora_19_weight", "old_id": "lora_19_weight"},
            {"new_id": "lora_20_enabled", "old_id": "lora_20_enabled"},
            {"new_id": "lora_20", "old_id": "lora_20"},
            {"new_id": "lora_20_weight", "old_id": "lora_20_weight"},
            {"new_id": "lora_21_enabled", "old_id": "lora_21_enabled"},
            {"new_id": "lora_21", "old_id": "lora_21"},
            {"new_id": "lora_21_weight", "old_id": "lora_21_weight"},
            {"new_id": "lora_22_enabled", "old_id": "lora_22_enabled"},
            {"new_id": "lora_22", "old_id": "lora_22"},
            {"new_id": "lora_22_weight", "old_id": "lora_22_weight"},
            {"new_id": "lora_23_enabled", "old_id": "lora_23_enabled"},
            {"new_id": "lora_23", "old_id": "lora_23"},
            {"new_id": "lora_23_weight", "old_id": "lora_23_weight"},
            {"new_id": "lora_24_enabled", "old_id": "lora_24_enabled"},
            {"new_id": "lora_24", "old_id": "lora_24"},
            {"new_id": "lora_24_weight", "old_id": "lora_24_weight"},
            {"new_id": "lora_25_enabled", "old_id": "lora_25_enabled"},
            {"new_id": "lora_25", "old_id": "lora_25"},
            {"new_id": "lora_25_weight", "old_id": "lora_25_weight"},
            {"new_id": "lora_26_enabled", "old_id": "lora_26_enabled"},
            {"new_id": "lora_26", "old_id": "lora_26"},
            {"new_id": "lora_26_weight", "old_id": "lora_26_weight"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
            {"new_idx": 1, "old_idx": 1},
            {"new_idx": 2, "old_idx": 2},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSPowerLoraMergerOptions",
        old_node_id="WASPowerLoraMergerOptions",
        old_widget_ids=["rank", "auto_rank_threshold", "preserve_norm", "cap_mult_enable", "cap_mult", "cpu", "include_patterns", "exclude_patterns", "moe_temperature", "moe_hard", "block_mix_weighted", "block_mix_concept_mix", "block_mix_style_mix"],
        input_mapping=[
            {"new_id": "rank", "old_id": "rank"},
            {"new_id": "auto_rank_threshold", "old_id": "auto_rank_threshold"},
            {"new_id": "preserve_norm", "old_id": "preserve_norm"},
            {"new_id": "cap_mult_enable", "old_id": "cap_mult_enable"},
            {"new_id": "cap_mult", "old_id": "cap_mult"},
            {"new_id": "dtype", "old_id": "dtype"},
            {"new_id": "compute_dtype", "old_id": "compute_dtype"},
            {"new_id": "cpu", "old_id": "cpu"},
            {"new_id": "include_patterns", "old_id": "include_patterns"},
            {"new_id": "exclude_patterns", "old_id": "exclude_patterns"},
            {"new_id": "moe_temperature", "old_id": "moe_temperature"},
            {"new_id": "moe_hard", "old_id": "moe_hard"},
            {"new_id": "block_mix_method", "old_id": "block_mix_method"},
            {"new_id": "block_mix_preset", "old_id": "block_mix_preset"},
            {"new_id": "block_mix_weighted", "old_id": "block_mix_weighted"},
            {"new_id": "block_mix_concept_mix", "old_id": "block_mix_concept_mix"},
            {"new_id": "block_mix_style_mix", "old_id": "block_mix_style_mix"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSSaveLUT",
        old_node_id="WASSaveLUT",
        old_widget_ids=["filename", "output_size", "overwrite"],
        input_mapping=[
            {"new_id": "lut", "old_id": "lut"},
            {"new_id": "filename", "old_id": "filename"},
            {"new_id": "output_size", "old_id": "output_size"},
            {"new_id": "overwrite", "old_id": "overwrite"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASNSTiledImageUpscaleWithModel",
        old_node_id="WASTiledImageUpscaleWithModel",
        old_widget_ids=["upscale_factor", "tile_size", "overlap", "feather", "clear_comfy_memory"],
        input_mapping=[
            {"new_id": "upscale_model", "old_id": "upscale_model"},
            {"new_id": "image", "old_id": "image"},
            {"new_id": "upscale_factor", "old_id": "upscale_factor"},
            {"new_id": "tile_size", "old_id": "tile_size"},
            {"new_id": "overlap", "old_id": "overlap"},
            {"new_id": "feather", "old_id": "feather"},
            {"new_id": "resample_method", "old_id": "resample_method"},
            {"new_id": "clear_comfy_memory", "old_id": "clear_comfy_memory"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASVAEEncodeForInpaint",
        old_node_id="VAEEncodeForInpaint (WAS)",
        old_widget_ids=["mask_offset"],
        input_mapping=[
            {"new_id": "pixels", "old_id": "pixels"},
            {"new_id": "vae", "old_id": "vae"},
            {"new_id": "mask", "old_id": "mask"},
            {"new_id": "mask_offset", "old_id": "mask_offset"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASVividSharpen",
        old_node_id="VividSharpen",
        old_widget_ids=["radius", "strength"],
        input_mapping=[
            {"new_id": "images", "old_id": "images"},
            {"new_id": "radius", "old_id": "radius"},
            {"new_id": "strength", "old_id": "strength"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
    io.NodeReplace(
        new_node_id="WASVividSharpenV2",
        old_node_id="VividSharpenV2",
        old_widget_ids=["radius_highpass", "radius_blur", "hp_brightness", "hp_contrast", "vivid_opacity", "overlay_opacity", "strength"],
        input_mapping=[
            {"new_id": "images", "old_id": "images"},
            {"new_id": "radius_highpass", "old_id": "radius_highpass"},
            {"new_id": "radius_blur", "old_id": "radius_blur"},
            {"new_id": "blur_mode", "old_id": "blur_mode"},
            {"new_id": "hp_brightness", "old_id": "hp_brightness"},
            {"new_id": "hp_contrast", "old_id": "hp_contrast"},
            {"new_id": "vivid_opacity", "old_id": "vivid_opacity"},
            {"new_id": "overlay_opacity", "old_id": "overlay_opacity"},
            {"new_id": "strength", "old_id": "strength"},
        ],
        output_mapping=[
            {"new_idx": 0, "old_idx": 0},
        ],
    ),
)


async def register_replacements() -> None:
    """Register every entry in :data:`REPLACEMENTS`. Called once from ``on_load``.

    Never raises: a failure is logged and the entries after it are left unregistered.
    """
    api = ComfyAPI()
    for index, replacement in enumerate(REPLACEMENTS):
        try:
            # register reaches into PromptServer.instance, absent outside a running server.
            await api.node_replacement.register(replacement)
        except Exception as error:
            logger.warning(
                "%s -> %s was not registered (%s), and %d further replacement(s) were not "
                "attempted; a workflow saved against one of those old node ids opens with "
                "that node missing and no swap offered for it",
                replacement.old_node_id, replacement.new_node_id, error,
                len(REPLACEMENTS) - index - 1,
            )
            return
    if REPLACEMENTS:
        logger.debug("registered %d node replacement(s)", len(REPLACEMENTS))
